[project]
authors = ["Sandeep Menon <s.menon@kodiak.ai>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "gsplat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
