[project]
authors = ["Sandeep Menon <s.menon@kodiak.ai>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "gsplat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
forward = "mojo run -I . -I tests tests/forward_test.mojo"
intersect = "mojo run -I . -I tests tests/intersect_test.mojo"
render-ply = "mojo run -I . -I tests tests/render_ply.mojo"
sh = "mojo run -I . -I tests tests/sh_test.mojo"

[dependencies]
max = "*"
